export default [
    { id: 1, title: "Strawberry Cake" },
    { id: 2, title: "Beef Fried Noodle" },
    { id: 3, title: "Shrimp"},
    { id: 4, title: "Hot Pot" },
    { id: 5, title: "Fish"},
    { id: 6, title: "Hainan Chicken"},
    { id: 7, title: "MeetFresh" },
    { id: 8, title: "Noodle" },
    { id: 9, title: "Peking Roast Duck" },
    { id: 10, title: "Pad Thai" }  ,
    { id: 11, title: "Fish" },
    { id: 12, title: "Pork" },
    { id: 13, title: "Orange Juice" },
    { id: 14, title: "Food" },
    { id: 15, title: "Rice Cake" },
    { id: 16, title: "Hainan Chicken" },
    { id: 17, title: "Rice Cake" },
    { id: 18, title: "Food" }
  ];